default_stages: [pre-commit]
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=50]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
        exclude: |
          (?x)^(
            src/file_manager/import_media.py|
            tests/test_import_media.py
          )
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: ["--python-version=3.12"]
        additional_dependencies: [types-requests>=2.20.0, pytest>=7.1.2, types-PyYaml>=6.0.0, types-dataclasses>=0.6.0]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.8.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
  - repo: https://github.com/crate-ci/typos
    rev: v1.15.9
    hooks:
      - id: typos
        exclude: |
          (?x)^(
            import_config.yaml
          )
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping=2, --sequence=4, --offset=2, --implicit_start, --preserve-quotes]
        additional_dependencies: [ruamel.yaml==0.17.21]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [--strict]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        always_run: true
        exclude: |
          (?x)^(
              test_data/.*\.(JPG|png)
          )$
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping=2, --sequence=4, --offset=2, --implicit_start, --preserve-quotes]
        additional_dependencies: [ruamel.yaml==0.17.21]
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.10.2
    hooks:
      - id: uv-lock
  - repo: https://github.com/executablebooks/mdformat
    # Stick to 0.7.17 since it is the last one supporting Python 3.8
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - linkify-it-py==1.0.3
          - mdformat-gfm==0.3.5
          - mdformat-myst==0.1.5
          - mdformat-shfmt==0.1.0
          - mdformat-config==0.1.3
          - mdformat-toc==0.3.0
  - repo: https://github.com/asottile/blacken-docs
    # Stick to 1.18.0 since it is the last one supporting Python 3.8
    rev: 1.18.0
    hooks:
      - id: blacken-docs
        args: [--line-length=120]
